"""Resume-tweak review dialog. STUB for this chunk: real Skills-only tweak
generation requires the Anthropic API + Drive/Docs clients (not built yet —
see the Phase 2 plan). Shows a clear placeholder instead of pretending it
works, per the honesty requirement on this feature."""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from PySide6.QtWidgets import QDialog, QLabel, QPushButton, QVBoxLayout  # noqa: E402


class TweakDialog(QDialog):
    def __init__(self, company: str, role: str, parent=None):
        super().__init__(parent)
        self.setWindowTitle(f"Adjust Resume — {company}")
        self.setMinimumWidth(420)

        layout = QVBoxLayout(self)
        layout.addWidget(QLabel(f"<b>{company} — {role}</b>"))

        message = QLabel(
            "Resume tweaking isn't implemented yet.\n\n"
            "Once built, this will show a before/after diff of just the "
            "Skills section — generated by selecting and re-ordering entries "
            "from your vetted Skills pool (never fabricated) — for you to "
            "Accept or Reject before it's used on an application."
        )
        message.setWordWrap(True)
        layout.addWidget(message)

        close_button = QPushButton("Close")
        close_button.clicked.connect(self.reject)
        layout.addWidget(close_button)
